config/routes.rb
Rails.application.routes.draw do
  # first form
  # get '/', controller: 'home', action: 'index'
  # get '/', to 'about#index'
  # second form
  root 'home#index'

  resources :vehicles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :brand, :model, :year, :kind, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  before_action :fetch_vehicle, only: %i[ show edit update destroy ]

  def index()
    @vehicles = Vehicle.all.order(created_at: :desc)
  end

  def new()
    @vehicle = Vehicle.new
  end

  def create()
    # quando mandarem uma requisicao para essa rota, eu quero que tenha os
    # paramentros de vehicles.
    @vehicle = Vehicle.new(vehicle_params)
    #guard clause
    return redirect_to vehicle_path(@vehicle) if @vehicle.save
    render :new
  end

  def show(); end

  def edit(); end

  def update()
    return redirect_to @vehicle if @vehicle.update(vehicle_params)
    render :edit
  end

  def destroy()
    @vehicle.destroy
    redirect_to vehicle_path
  end

  private

  def vehicle_params() #strong parameters, verifica os parametros
    params.require(:vehicle).permit(:brand, :model, :year, :kind)
  end

  def fetch_vehicle()
    @vehicle = Vehicle.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>Hello world</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_erros.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <p>
      <%= message %>
    </p>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <%= link_to root_path do %>
    <h1>Home</h1>
  <% end %>
  <%= link_to 'Vehicles', vehicles_path %>
</nav>

app/views/shared/erros.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <p>
      <%= message %>
    </p>
  <% end %>
<% end %>

app/views/vehicles/_form.html.erb
<%= form_with model: vehicle, data: {turbo: false} do |form| %>
  <p>
    <%= form.label :brand, 'brand' %>
    <%= form.text_field :brand %>
  </p>
  <p>
    <%= form.label :model, 'model' %>
    <%= form.text_field :model %>
  </p>
  <p>
    <%= form.label :year, 'year' %>
    <%= form.number_field :year %>
  </p>
  <p>
    <%= form.label :kind, 'kind' %>
    <%= form.number_field :kind %>
  </p>
  <p>
    <%= form.submit 'Create' %>
  </p>

  <% if action_name == 'edit' %>
    Estou no Edit
  <% elsif action_name == 'new' %>
    Estou no new
  <% end %>
<% end %>

app/views/vehicles/_vehicle.html.erb
<p>
    <%= vehicle.id %> |
    <%= vehicle.brand %> |
    <%= vehicle.model %> |
    <%= vehicle.year %> |
    <%= vehicle.kind %> |
    <%= link_to 'Details', vehicle_path(vehicle) %>
    <%= link_to 'Edit', edit_vehicle_path(vehicle) %>
    <%= link_to 'Erase', vehicle_path(vehicle), data: { 'turbo-method': :delete, 'turbo-confirm': 'Confirma a ação de deletar?'} %>
  </p>

app/views/vehicles/edit.html.erb
<h2>Edit Vehicle</h2>

<% if @vehicle.errors.any? %>
  <% @vehicle.errors.full_messages.each do |message| %>
    <p>
      <%= message %>
    </p>
  <% end %>
<% end %>

<%= render 'form', vehicle: @vehicle %>

app/views/vehicles/index.html.erb
<h2>Vehicles</h2>

<p>
  <%= link_to "New Vehicle", new_vehicle_path %>
</p>


<%= render @vehicles %>

app/views/vehicles/new.html.erb
<h2>New vehicle</h2>

<% if @vehicle.errors.any? %>
  <% @vehicle.errors.full_messages.each do |message| %>
    <p>
      <%= message %>
    </p>
  <% end %>
<% end %>

<%= render 'shared/erros' object: @vehicle %>
<%= render 'form', vehicle: @vehicle %>

app/views/vehicles/show.html.erb
<h2>Vehicle - id: <%= @vehicle.id %> </h2>

<p>
  <%= @vehicle.brand %> |
  <%= @vehicle.model %> |
  <%= @vehicle.year %> |
  <%= @vehicle.kind %> |
</p>